//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsidWebExerciseDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Stores
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }

        [DisplayName("Store Name")]
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$")]
        //[Required(ErrorMessage = "Store Name is required.")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Address is required.")] //occurs ModelState.Isvalid = false
        public string Address { get; set; }

        //[Required(ErrorMessage = "City is required.")] 
        public string City { get; set; }

        [MinLength(5, ErrorMessage = "Zip-number must contains of 5 numbers.")]
        [MaxLength(5, ErrorMessage = "Zip-number must contains of 5 numbers.")]
        //[Required(ErrorMessage = "Zip-number is required.")]
        public string Zip { get; set; }

        //[Required(ErrorMessage = "Country is required.")]
        public string Country { get; set; }

        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual Companies Companies { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
